# Step 2 Helper - Instagram API Setup Script
# Run this to generate the exact configuration once you have credentials

import json
from pathlib import Path

def setup_mcp_integration():
    """
    Interactive setup for Instagram MCP integration
    Run this after completing Step 2 manually
    """
    print("🐼 Hungry Panda - Instagram MCP Setup Helper")
    print("=" * 50)
    print()
    print("This script will help you configure Hungry Panda with Instagram MCP.")
    print("You should have already:")
    print("  1. Converted Instagram to Business/Creator account")
    print("  2. Connected it to a Facebook Page")
    print("  3. Created a Facebook App")
    print("  4. Generated an access token")
    print()
    
    # Collect credentials
    config = {}
    
    print("📋 Enter your Instagram details:")
    config['INSTAGRAM_USERNAME'] = input("Instagram username (no @): ").strip()
    config['INSTAGRAM_ACCOUNT_TYPE'] = input("Account type (business/creator): ").strip().lower()
    config['INSTAGRAM_BUSINESS_ACCOUNT_ID'] = input("Instagram Business Account ID: ").strip()
    
    print()
    print("📋 Enter your Facebook App credentials:")
    config['INSTAGRAM_APP_ID'] = input("Facebook App ID: ").strip()
    config['INSTAGRAM_APP_SECRET'] = input("Facebook App Secret: ").strip()
    config['INSTAGRAM_ACCESS_TOKEN'] = input("Long-lived Access Token: ").strip()
    
    print()
    print("📋 MCP Configuration:")
    mcp_path = input("Path to ig-mcp server (or leave blank for auto): ").strip()
    if mcp_path:
        config['MCP_SERVER_PATH'] = mcp_path
    
    # Generate .env file
    env_content = f"""# Hungry Panda Configuration - Generated by setup helper
# Instagram Account
INSTAGRAM_USERNAME={config['INSTAGRAM_USERNAME']}
INSTAGRAM_ACCOUNT_TYPE={config['INSTAGRAM_ACCOUNT_TYPE']}

# Instagram API (for MCP)
INSTAGRAM_APP_ID={config['INSTAGRAM_APP_ID']}
INSTAGRAM_APP_SECRET={config['INSTAGRAM_APP_SECRET']}
INSTAGRAM_ACCESS_TOKEN={config['INSTAGRAM_ACCESS_TOKEN']}
INSTAGRAM_BUSINESS_ACCOUNT_ID={config['INSTAGRAM_BUSINESS_ACCOUNT_ID']}

# MCP Integration
ENABLE_MCP_INTEGRATION=true
MCP_SERVER_TYPE=ig-mcp
POSTING_METHOD=mcp
MCP_SERVER_PATH={config.get('MCP_SERVER_PATH', '')}

# Server Settings
HOST=0.0.0.0
PORT=8000
DEBUG=false

# Feature Flags
ENABLE_COMPETITOR_TRACKING=true
ENABLE_AUTO_CAPTIONS=true
ENABLE_AUTO_HASHTAGS=true
ENABLE_ANALYTICS=true
"""
    
    # Write to file
    env_path = Path(__file__).parent.parent / "config" / ".env"
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print()
    print("✅ Configuration saved to:", env_path)
    print()
    print("🚀 Next steps:")
    print("  1. Install ig-mcp server:")
    print("     git clone https://github.com/jlbadano/ig-mcp.git")
    print("  2. Start Hungry Panda:")
    print("     cd backend && python main.py")
    print()
    print("📚 Documentation:")
    print("  - docs/MCP_INTEGRATION.md")
    print("  - docs/INSTAGRAM_SETUP.md")

if __name__ == "__main__":
    setup_mcp_integration()
